version: '3.7'

services:
  order-ws:
    image: payment-ws:latest
    container_name: payment-ws
    build: .
    ports:
      - '8098:8098'
    depends_on:
      - database
    networks:
      - mvp-network

  database:
    image: 'mongo:latest'
    container_name: 'mongodb'
    ports:
      - '27017:27017'
    environment:
      TZ: 'America/Sao_Paulo'
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - mvp-network

networks:
  mvp-network:
    driver: bridge
