server:
  port: 8098
  servlet:
    contextPath: "/"
  error:
    include-message: always

spring-doc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  profiles:
    active: production
  data:
    mongodb:
      uri: "${SPRING_DATA_MONGODB_URI:mongodb://mongodb:mongodb@mongodb:27017/paymentdb?authSource=admin}"
    allow-bean-definition-overriding: true
  docker:
    compose:
      file: "docker-compose.yml"

logging:
  level:
    root:
      org.springframework.web: "debug"
      org.hibernate: "debug"

cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      instance-profile: true
    stack:
      auto: false

order:
  mp-api:
    token: "${TOKEN_API}"
    userId: "${USER_ID}"
    sponsorId: "S{SPONSOR_ID}"
    url: "https://api.mercadopago.com/"
    notificationUrl: "${NOTIFICATION_URL}"
  api-endpoints:
    qrs: "instore/orders/qr/seller/collectors/?/pos/?/qrs"

aws:
  region: us-east-1
  topicArn: "${TOPIC_ORDER_SNS:arn:aws:sns:us-east-1:1111111:ORDER_TOPIC}"
  statusQueue: "${STATUS_QUEUE:https://sqs.us-east-1.amazonaws.com/1111111/STATUS_QUEUE}"